#inherit_from:
#  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'vendor/**/*' # need to reset this apparently
    - 'lib/yard/parser/ruby/legacy/ruby_lex.rb' # old file, don't touch
Metrics:
  Enabled: false
Style/Semicolon:
  AllowAsExpressionSeparator: true
Style/Documentation:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/NumericPredicate: # ruby 1.8/1.9 do not have positive?/negative?
  EnforcedStyle: comparison
Layout/DotPosition:
  EnforcedStyle: trailing
Style/FormatString:
  EnforcedStyle: percent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# Disable these until we know what to do with them
Style/SafeNavigation:
  Enabled: false # not supported in 1.8...2.1
Style/GuardClause: # does not provide much value
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Naming/AccessorMethodName: # this creates breaking changes in the API
  Enabled: false
Naming/PredicateName: # this creates breaking changes in the API
  Enabled: false
Style/MethodMissingSuper: # this doesn't exist in 1.8/1.9
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Style/Lambda: # not supported in 1.8
  Enabled: false
Style/EachWithObject: # not supported in 1.8
  Enabled: false
Layout/ParameterAlignment: # does not work correctly with subsequent block
  Enabled: false
Layout/ArrayAlignment: # does not support indentation
  Enabled: false
Layout/HashAlignment: # does not support indentation
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true
Style/SingleLineMethods:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/NestedTernaryOperator:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/WhenThen:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/BlockComments:
  Exclude:
    - benchmarks/*.rb
Style/CaseEquality:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/GlobalVars:
  Exclude:
    - benchmarks/**/*.rb
    - spec/**/*.rb
Lint/RedundantSplatExpansion:
  Enabled: false
Security/Eval:
  Exclude:
    - benchmarks/**/*.rb
    - spec/**/*.rb
